script: ./travis-build.sh
sudo: false
jdk:
- openjdk7
env:
  global:
  - GRADLE_OPTS="-server -Xmx1024M -Xms768M -XX:PermSize=256m -XX:MaxPermSize=512m"
  - GIT_NAME="Graeme Rocher"
  - GIT_EMAIL="graeme.rocher@gmail.com"
  - secure: XYCwEEGptpfz4Fq5F4EldLPvxWrywk07vRsHQt0TEWfsB4uomG546H/Rs7hnWIl3o0NRo9g48vCC/wpdWSmMaSEcAiHKOlSae+6B7t9L5yFpU4/+nNZaTDa2aaAwHfFihkDcFu2ct6jRkKOgtjDYfU8rolgr04ciwJxCzybpZAY=
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
deploy:
  provider: releases
  api_key:
    secure: OXqyhH6/rK9rmiApnm+8smg/+rjdM3T28/4ZUzbdibYZNSagVAMniDgndZIwt198jDvAPxf9jadN1G3OD5BLkW0wUWvAfYAtxAwOe6dzgcsMavdTxoBJnjXBc4XqFXSDhWTO4cd4vQ5Wx6cyvbUY5xgyREpvEP7oRUgQ0RJo9q8=
  file: build/distributions/grails-docs-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  on:
    repo: grails/grails-doc
    tags: true
    all_branches: true
